title: Configuration du site

tabs:
  toutes_rubriques:
    label: Toutes les rubriques
    icon: folder
    columns:
      - width: 2/3
        sections:


          main_pages:
            type: pages
            headline: Toutes les rubriques
            layout: cardlets
            status: listed
            query: site.children.listed()
            info: "{{ page.children.count }} élements"

          home_image:
            type: fields
            fields:
              home_cover:
                label: Image page d'accueil
                type: files
                multiple: false
                layout: cards
                uploads: true
                query: site.files
                width: 1/3
                info: "{{ file.dimensions }}"
 
                

      - width: 1/3
        sections:
          drafts_all:
            type: pages
            headline: Brouillons (tout le site)
            layout: list
            status: draft
            query: site.index.drafts()
            sortBy: date desc
            create: false

  mentions_legales:
    label: Mentions légales
    icon: cog
    columns:
      - width: 1/2
        sections:
          mentions_page:  
            type: pages
            headline: Mentions légales
            template: mentions-legales
            layout: list